# see https://gitlab.com/help/ci/yaml/README.md#jobs
# Select image
image: my:php
stages:
  - phplint
  - phpfixer
  - build
  - test
  - deploy

# php lint
phplint:
  stage: phplint
  script:
  - bash php/bin/phplint.sh

# php code style
phpfixer:
  stage: phpfixer
  script:
  - bash php/bin/phpfixer.sh

# unit test
test:
  stage: test
  script:
  - cd php
  - composer install
  - bash bin/test.sh
