name: run unit test

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: php-actions/composer@v1
      with:
          command: '-V'
    - name: composer install
      run: cd ./practice/tests && composer install
    - name: run phpunit
      run: chmod +x . -R && ./practice/tests/bin/phpunit.sh
